export const USER_LIST_REQUEST = 'USER_LIST_REQUEST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAIL = 'USER_LIST_FAIL';
export const USER_LIST_RESET = 'USER_LIST_RESET';

export const USER_DELETE_REQUEST = 'USER_DELETE_REQUEST';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAIL = 'USER_DELETE_FAIL';

export const ADMIN_USER_DETAIL_REQUEST = 'ADMIN_USER_DETAIL_REQUEST';
export const ADMIN_USER_DETAIL_SUCCESS = 'ADMIN_USER_DETAIL_SUCCESS';
export const ADMIN_USER_DETAIL_FAIL = 'ADMIN_USER_DETAIL_FAIL';
export const ADMIN_USER_DETAIL_RESET = 'ADMIN_USER_DETAIL_RESET';

export const ADMIN_USER_UPDATE_REQUEST = 'ADMIN_USER_UPDATE_REQUEST';
export const ADMIN_USER_UPDATE_SUCCESS = 'ADMIN_USER_UPDATE_SUCCESS';
export const ADMIN_USER_UPDATE_FAIL = 'ADMIN_USER_UPDATE_FAIL';
export const ADMIN_USER_UPDATE_RESET = 'ADMIN_USER_UPDATE_RESET';

export const ADMIN_PRODUCT_DELETE_REQUEST = 'ADMIN_PRODUCT_DELETE_REQUEST';
export const ADMIN_PRODUCT_DELETE_SUCCESS = 'ADMIN_PRODUCT_DELETE_SUCCESS';
export const ADMIN_PRODUCT_DELETE_FAIL = 'ADMIN_PRODUCT_DELETE_FAIL';

export const ADMIN_PRODUCT_CREATE_REQUEST = 'ADMIN_PRODUCT_CREATE_REQUEST';
export const ADMIN_PRODUCT_CREATE_SUCCESS = 'ADMIN_PRODUCT_CREATE_SUCCESS';
export const ADMIN_PRODUCT_CREATE_FAIL = 'ADMIN_PRODUCT_CREATE_FAIL';
export const ADMIN_PRODUCT_CREATE_RESET = 'ADMIN_PRODUCT_CREATE_RESET';

export const ADMIN_PRODUCT_DETAIL_REQUEST = 'ADMIN_PRODUCT_DETAIL_REQUEST';
export const ADMIN_PRODUCT_DETAIL_SUCCESS = 'ADMIN_PRODUCT_DETAIL_SUCCESS';
export const ADMIN_PRODUCT_DETAIL_FAIL = 'ADMIN_PRODUCT_DETAIL_FAIL';
export const ADMIN_PRODUCT_DETAIL_RESET = 'ADMIN_PRODUCT_DETAIL_RESET';

export const ADMIN_PRODUCT_UPDATE_REQUEST = 'ADMIN_PRODUCT_UPDATE_REQUEST';
export const ADMIN_PRODUCT_UPDATE_SUCCESS = 'ADMIN_PRODUCT_UPDATE_SUCCESS';
export const ADMIN_PRODUCT_UPDATE_FAIL = 'ADMIN_PRODUCT_UPDATE_FAIL';
export const ADMIN_PRODUCT_UPDATE_RESET = 'ADMIN_PRODUCT_UPDATE_RESET';
export const ADMIN_ORDER_LIST_REQUEST = 'ADMIN_ORDER_LIST_REQUEST';
export const ADMIN_ORDER_LIST_SUCCESS = 'ADMIN_ORDER_LIST_SUCCESS';
export const ADMIN_ORDER_LIST_FAIL = 'ADMIN_ORDER_LIST_FAIL';
export const ADMIN_ORDER_DELIVER_REQUEST = 'ADMIN_ORDER_DELIVER_REQUEST';
export const ADMIN_ORDER_DELIVER_SUCCESS = 'ADMIN_ORDER_DELIVER_SUCCESS';
export const ADMIN_ORDER_DELIVER_FAIL = 'ADMIN_ORDER_DELIVER_FAIL';
export const ADMIN_ORDER_DELIVER_RESET = 'ADMIN_ORDER_DELIVER_RESET';
